### ISSUE TITLE
🚀  Add daemon feature to dawn.

### ISSUE THREAD

**Issue by kiyonlin** [kiyonlin/dawn#3]
**Describe the solution you'd like**
Add daemon feature to dawn. Get options from global config.

**Additional context**
When daemon is enabled, dawn app can restart itself automatically when it crashes.

**Comment by kiyonlin** [comment]
**🌶️   Notice**
-
-  `go run` won't work in daemon mode
-  Please use `go build` to build a binary and run it

**📔 Usage**
- 

Set daemon options in `config.toml`
```toml
[Daemon]
Enable = true
Tries = 10
StdoutLogFile = "./daemon.log"
StderrLogFile = "./daemon.err"
```
And reference [example](https://github.com/kiyonlin/dawn/blob/master/_examples/daemon/main.go) for more details.
